
import ProviderWraper from "./components/ProviderWraper";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ProviderWraper>{children}</ProviderWraper>
      </body>
    </html>
  );
}

