import React from "react";
import LeftSideBar from "./components/LeftSideBar";
import { SidebarProvider } from "@/components/ui/sidebar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BrowseLayout({ children }) {
  return (
    <div
      className="w-screen h-screen overflow-hidden flex"
    >
      <SidebarProvider>
        <LeftSideBar />
        <section className="grow">
          {children}
        </section>
      </SidebarProvider>
    </div>
  );
}
