import LeftSideBar from "./components/LeftSideBar";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BrowseLayout({ children }) {
  return (
        <div
          className="w-screen h-screen overflow-hidden flex"
        >
          <LeftSideBar />
          <section className="grow">
            {children}
          </section>
        </div>
  );
}
